server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

service:
  order:
    url: http://localhost:8081

feign:
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 5000
  circuitbreaker:
    enabled: true

resilience4j:
  retry:
    instances:
      orderService:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: false
        retry-exceptions:
          - feign.FeignException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - org.springframework.web.client.ResourceAccessException
  circuitbreaker:
    instances:
      orderService:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 3000ms
        wait-duration-in-open-state: 5000ms
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
  ratelimiter:
    instances:
      orderService:
        limit-for-period: 5
        limit-refresh-period: 1s
        timeout-duration: 200ms

axon:
  axonserver:
    servers: localhost:8124
    enabled: true
  distributed-command-bus:
    enabled: false
  eventhandling:
    processors:
      payments:
        mode: tracking
    tokenstore:
      jpa:
        enabled: true

logging:
  level:
    com.paymentservice: INFO
    io.github.resilience4j: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG
    io.github.resilience4j.retry: DEBUG
    io.github.resilience4j.ratelimiter: DEBUG
    org.springframework.cloud.openfeign: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    enable
