# ===================== SERVER =====================
server:
  port: 0   # port dynamique, à surcharger au lancement si nécessaire (--server.port=8086 ou 8087)

# ===================== DATASOURCE =====================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# ===================== SERVICES EXTERNES =====================
service:
  order:
    url: http://localhost:8081

feign:
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 5000
  circuitbreaker:
    enabled: true

# ===================== RESILIENCE4J =====================
resilience4j:
  retry:
    instances:
      orderService:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: false
        retry-exceptions:
          - feign.FeignException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - org.springframework.web.client.ResourceAccessException
  circuitbreaker:
    instances:
      orderService:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 3000ms
        wait-duration-in-open-state: 5000ms
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
  ratelimiter:
    instances:
      orderService:
        limit-for-period: 5
        limit-refresh-period: 1s
        timeout-duration: 200ms

# ===================== AXON =====================
axon:
  axonserver:
    servers: localhost:8124
    enabled: true
  distributed-command-bus:
    enabled: false
  eventhandling:
    processors:
      payments:
        mode: tracking
    tokenstore:
      jpa:
        enabled: true

# ===================== LOGGING =====================
logging:
  level:
    com.paymentservice: INFO
    io.github.resilience4j: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG
    io.github.resilience4j.retry: DEBUG
    io.github.resilience4j.ratelimiter: DEBUG
    org.springframework.cloud.openfeign: DEBUG

# ===================== MANAGEMENT / PROMETHEUS =====================
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always

# ===================== CONSEIL POUR LE DEMARRAGE =====================
# Pour lancer deux instances avec ports fixes à la place du port dynamique :
# java -jar payment-service.jar --server.port=8086
# java -jar payment-service.jar --server.port=8087
