

axon:
  axonserver:
    servers: localhost:8124
    enabled: true
  distributed-command-bus:
    enabled: true  
  eventhandling:
    processors:
      # Définir un processor pour les événements de commandes
      stock-management:
        mode: tracking  
        source: eventStore
        event-availability-timeout: 1000

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    io.github.resilience4j: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
    instances:
      productService:
        baseConfig: default
      userService:
        baseConfig: default
        slidingWindowSize: 20
        failureRateThreshold: 60

  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - java.lang.IllegalArgumentException
    instances:
      productService:
        baseConfig: default
      userService:
        baseConfig: default
        maxAttempts: 5
        waitDuration: 1000ms

  ratelimiter:
    configs:
      default:
        registerHealthIndicator: true
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 0s
        eventConsumerBufferSize: 100
    instances:
      productService:
        baseConfig: default
      createProduct:
        limitForPeriod: 3
        limitRefreshPeriod: 1s
        timeoutDuration: 0s

  timelimiter:
    configs:
      default:
        timeoutDuration: 2s
        cancelRunningFuture: true
    instances:
      productService:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: >
          health,
          info,
          prometheus,
          metrics,
          circuitbreakers,
          ratelimiters,
          retries

  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

  metrics:
    tags:
      application: product-service




