server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  axon:
    axonserver:
      servers: localhost:8124
      context: default
    eventstore:
      jpa:
        schema-generation:
          enabled: true
    eventhandling:
      processors:
        user:
          mode: subscribing
          source: eventStore
          initial-segment-count: 1

axoniq:
  axonserver:
    default-command-timeout: 30000
    command-timeout: 60000
    heartbeat-interval: 5000
    heartbeat-timeout: 15000
resilience4j:
    retry:
      instances:
        userServiceRetry:
          maxAttempts: 3
          waitDuration: 500ms
          enableExponentialBackoff: false

    ratelimiter:
      instances:
        userServiceRateLimiter:
          limitForPeriod: 5                    # 5 requêtes par seconde
          limitRefreshPeriod: 1s
          timeoutDuration: 0ms

    circuitbreaker:
      instances:
        userServiceCircuitBreaker:
          failureRateThreshold: 50             # % d'échecs pour ouvrir le circuit
          waitDurationInOpenState: 10s
          permittedNumberOfCallsInHalfOpenState: 3
          slidingWindowSize: 100
          slidingWindowType: COUNT_BASED
          minimumNumberOfCalls: 20
          recordExceptions:
            - java.lang.Exception
            - org.springframework.web.client.ResourceAccessException

management:
    endpoints:
      web:
        exposure:
          include: health, info, prometheus, metrics
    endpoint:
      health:
        show-details: always
    metrics:
      export:
        prometheus:
          enabled: true